# Generated by Django 5.0.2 on 2024-02-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(default='bill-name', max_length=20)),
                ('amount', models.IntegerField()),
                ('split_type', models.CharField(default='EQUAL', max_length=20)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='expense.group')),
            ],
        ),
    ]
