# Generated by Django 5.0.2 on 2024-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_billuser_debt_bill_repayments_group_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(),
        ),
    ]
