# Generated by Django 5.0.2 on 2024-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='users',
            field=models.ManyToManyField(to='expense.billuser'),
        ),
    ]
