# Generated by Django 5.0.2 on 2024-02-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_bill_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='group_id',
            new_name='group',
        ),
    ]
