# Generated by Django 5.0.2 on 2024-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_rename_group_id_bill_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
