# Generated by Django 5.0.2 on 2024-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_bill_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bill_images/'),
        ),
    ]
